# Generated by Django 2.2.3 on 2019-07-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='shoes_image',
            field=models.URLField(null=True),
        ),
    ]
